import './styles.css';
const API = import.meta.env.VITE_API_URL || 'http://localhost:8003/api';
const $ = (s) => document.querySelector(s);
const esc = (v) => String(v ?? '').replace(/[&<>"']/g, (c) => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt = (v, digits = 2) => Number(v).toFixed(digits);
const labels = {annual_income_k:'Annual income', spend_score:'Spend score', purchase_frequency:'Purchase frequency', avg_order_value:'Average order value'};
const state = {summary:null, points:[], filter:'all', x:'annual_income_k', y:'spend_score', selected:null};

async function get(path) { const response = await fetch(`${API}${path}`); if (!response.ok) throw new Error(`${response.status} ${path}`); return response.json(); }
function profileRows() {
  const groups = new Map();
  state.points.forEach((p) => { if (!groups.has(p.cluster)) groups.set(p.cluster, []); groups.get(p.cluster).push(p); });
  return [...groups].map(([cluster, rows]) => ({cluster, rows, mean: Object.fromEntries(Object.keys(labels).map((k) => [k, rows.reduce((s,r)=>s+Number(r[k]),0)/rows.length]))}));
}
function render() {
  const s = state.summary; const profiles = profileRows();
  $('#app').innerHTML = `<header class="topbar"><a class="brand" href="#top"><span class="mark">03</span><span><b>SEGMENT ATLAS</b><small>Customer clustering laboratory</small></span></a><nav><a href="#profiles">Profiles</a><a href="#explorer">Explorer</a><a href="#method">Method</a></nav><span class="status">● API VERIFIED</span></header>
  <main id="top"><section class="hero"><div><p class="eyebrow">CMPE 255 · UNSUPERVISED LEARNING</p><h1>Find the shape<br/><em>inside the customer base.</em></h1><p class="lede">A reproducible clustering lab for turning behavioral features into inspectable customer hypotheses.</p><div class="hero-actions"><a class="primary" href="#explorer">Explore points ↓</a><span class="quiet">${s.n_customers} synthetic records · seed ${s.seed}</span></div></div><div class="hero-orbit"><div class="orbit-card"><span>SELECTED RUN</span><strong>k = ${s.selected_k}</strong><small>${esc(s.selected_preprocessing)} preprocessing</small></div></div></section>
  <section class="metrics"><article><span>HELD-OUT SILHOUETTE</span><strong>${fmt(s.validation.silhouette_mean,4)}</strong><small>mean ± ${fmt(s.validation.silhouette_std,4)}</small></article><article><span>PARTITION STABILITY</span><strong>${fmt(s.validation.stability_ari_mean,4)}</strong><small>ARI across repeated fits</small></article><article><span>FEATURE SPACE</span><strong>${s.features.length}</strong><small>scaled dimensions · no labels</small></article><article><span>RUN STATUS</span><strong class="green">READY</strong><small>manifest and hashes verified</small></article></section>
  <section id="profiles" class="section"><div class="section-head"><div><p class="eyebrow">01 / INTERPRETATION</p><h2>Segments are hypotheses,<br/><em>not truths.</em></h2></div><p class="section-copy">K-Means finds geometric groupings. The profile cards translate those groupings into cautious business language so you can inspect before acting.</p></div><div class="profile-grid">${profiles.map((p,i)=>`<article class="profile"><div class="profile-top"><span>SEGMENT ${p.cluster}</span><strong>${p.rows.length}<small> customers</small></strong></div><h3>${['Budget starters','Frequent loyalists','Premium value'][i] || `Cluster ${p.cluster}`}</h3><p class="hypothesis">${i===0?'Lower observed value and frequency.':i===1?'Higher engagement in this toy sample.':'Larger average orders in this toy sample.'} <b>Hypothesis only.</b></p>${Object.keys(labels).map(k=>`<div class="barline"><span>${labels[k]}</span><b>${fmt(p.mean[k],1)}</b><i><u style="width:${Math.min(100,Math.max(8,p.mean[k]/Math.max(...profiles.map(x=>x.mean[k]))*100))}%"></u></i></div>`).join('')}</article>`).join('')}</div></section>
  <section id="explorer" class="section explorer-section"><div class="section-head"><div><p class="eyebrow">02 / POINT INSPECTOR</p><h2>Interrogate<br/><em>the assignment.</em></h2></div><p class="section-copy">Select a point to inspect raw features and geometry diagnostics. The assignment confidence is a distance proxy—not a probability.</p></div><div class="toolbar"><label>Segment <select id="cluster-filter"><option value="all">All segments</option>${profiles.map(p=>`<option value="${p.cluster}">Segment ${p.cluster}</option>`).join('')}</select></label><label>X axis <select id="x-axis">${Object.keys(labels).map(k=>`<option value="${k}">${labels[k]}</option>`).join('')}</select></label><label>Y axis <select id="y-axis">${Object.keys(labels).map(k=>`<option value="${k}">${labels[k]}</option>`).join('')}</select></label><span id="point-count"></span></div><div class="explorer-grid"><div class="plot-panel" id="plot"></div><aside class="inspector" id="inspector"><span class="eyebrow">POINT INSPECTOR</span><h3>Select a customer point</h3><p>Every point is a generated record with a cluster assignment and geometry diagnostics.</p></aside></div></section>
  <section class="section estimator"><div><p class="eyebrow">03 / API PREDICTION</p><h2>Score a new<br/><em>customer profile.</em></h2><p class="section-copy">This form calls the FastAPI scoring endpoint using the exact fitted preprocessing and K-Means model path.</p></div><form id="score-form">${Object.keys(labels).map(k=>`<label>${labels[k]}<input name="${k}" type="number" step="0.1" value="${k==='annual_income_k'?65:k==='spend_score'?60:k==='purchase_frequency'?4:70}" min="0" required></label>`).join('')}<button class="primary" type="submit">Score via API ↗</button><output id="score-result">Ready for an observation.</output></form></section>
  <section id="method" class="method"><p class="eyebrow">CRISP-DM TRACE</p><div class="method-grid"><div><strong>01 · Prepare</strong><p>Validate domains, compare StandardScaler and log1p variants, and fit preprocessing inside each validation split.</p></div><div><strong>02 · Model</strong><p>Fit K-Means across predeclared k=2…7 candidates with a deterministic seed and repeated holdouts.</p></div><div><strong>03 · Evaluate</strong><p>Use held-out silhouette and ARI stability for selection; full-sample metrics remain descriptive diagnostics.</p></div><div><strong>04 · Use carefully</strong><p>Explore segments as hypotheses. Validate on real longitudinal outcomes before operational decisions.</p></div></div></section></main><footer>PROJECT 03 · LOCAL EVIDENCE API · SYNTHETIC TEACHING SAMPLE</footer>`;
  $('#cluster-filter').value=state.filter; $('#x-axis').value=state.x; $('#y-axis').value=state.y; $('#cluster-filter').onchange=e=>{state.filter=e.target.value;renderExplorer()}; $('#x-axis').onchange=e=>{state.x=e.target.value;renderExplorer()}; $('#y-axis').onchange=e=>{state.y=e.target.value;renderExplorer()}; $('#score-form').onsubmit=score;
  renderExplorer();
}
function visible(){return state.points.filter(p=>state.filter==='all'||String(p.cluster)===state.filter)}
function renderExplorer(){const rows=visible(); $('#point-count').textContent=`${rows.length} of ${state.points.length} points`; const w=760,h=410,p=52; const xs=rows.map(r=>+r[state.x]),ys=rows.map(r=>+r[state.y]); const scale=(v,a,b)=>p+(v-Math.min(...a))/(Math.max(...a)-Math.min(...a)||1)*(w-p*1.5); const sy=(v,a,b)=>h-p-(v-Math.min(...a))/(Math.max(...a)-Math.min(...a)||1)*(h-p*1.5); $('#plot').innerHTML=`<svg viewBox="0 0 ${w} ${h}" role="img" aria-label="Customer clustering scatter plot"><line x1="${p}" y1="${h-p}" x2="${w-p/2}" y2="${h-p}"/><line x1="${p}" y1="${p/2}" x2="${p}" y2="${h-p}"/><text x="${w/2}" y="${h-8}">${labels[state.x]}</text><text transform="translate(14 ${h/2}) rotate(-90)">${labels[state.y]}</text>${rows.map(r=>`<circle class="dot ${r.customer_id===state.selected?'selected':''}" cx="${scale(r[state.x],xs)}" cy="${sy(r[state.y],ys)}" r="${r.customer_id===state.selected?8:5}" fill="${['#ee7860','#78b8ad','#e6b75c'][r.cluster%3]}" data-id="${esc(r.customer_id)}" tabindex="0" role="button" aria-label="${esc(r.customer_id)}, segment ${r.cluster}"/>`).join('')}</svg>`; document.querySelectorAll('.dot').forEach(d=>d.onclick=()=>select(d.dataset.id)); if(state.selected)select(state.selected)}
function select(id){state.selected=id;const r=state.points.find(p=>p.customer_id===id);if(!r)return;$('#inspector').innerHTML=`<span class="eyebrow">POINT INSPECTOR · ${esc(r.customer_id)}</span><h3>Segment ${r.cluster}</h3><p class="hypothesis"><b>${esc(r.uncertainty_label)} assignment.</b> Geometry diagnostic, not a probability.</p><div class="detail-grid">${Object.keys(labels).map(k=>`<div><span>${labels[k]}</span><strong>${fmt(r[k],1)}</strong></div>`).join('')}</div><div class="diagnostics"><span>Distance <b>${fmt(r.centroid_distance,3)}</b></span><span>Margin <b>${fmt(r.assignment_margin,3)}</b></span><span>Proxy <b>${fmt(r.assignment_confidence,3)}</b></span></div>`; document.querySelectorAll('.dot').forEach(d=>d.classList.toggle('selected',d.dataset.id===id))}
async function score(e){e.preventDefault();const out=$('#score-result');out.textContent='Scoring…';const data=Object.fromEntries(new FormData(e.target));try{const r=await fetch(`${API}/score`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(Object.fromEntries(Object.entries(data).map(([k,v])=>[k,Number(v)])))});const body=await r.json();if(!r.ok)throw new Error(body.detail||'Request failed');out.innerHTML=`Assigned to <b>Segment ${body.cluster}</b> · ${esc(body.preprocessing)} · ${body.note}`}catch(err){out.textContent=`API error: ${err.message}`}}
async function boot(){try{[state.summary,state.points]=await Promise.all([get('/summary'),get('/points')]);render()}catch(err){$('#app').innerHTML=`<main class="error"><h1>Evidence API unavailable</h1><p>Start the FastAPI server on port 8003, then reload this client.</p><code>${esc(err.message)}</code></main>`}} boot();
