import "./styles.css";

const API = import.meta.env.VITE_API_URL || "http://127.0.0.1:8003/api";
const FEATURES = {
  annual_income_k: "Annual income ($k)",
  spend_score: "Spend score",
  purchase_frequency: "Purchase frequency",
  avg_order_value: "Average order value"
};
const state = { summary: null, profiles: [], points: [], cluster: "all", x: "spend_score", y: "annual_income_k", projection: "raw", selected: null };
const $ = (selector) => document.querySelector(selector);
const esc = (value) => String(value).replace(/[&<>"']/g, (c) => ({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));
const fmt = (value, digits = 2) => Number(value).toLocaleString(undefined, { maximumFractionDigits: digits });

async function get(path) {
  const response = await fetch(`${API}${path}`);
  if (!response.ok) throw new Error(`API request failed: ${response.status}`);
  return response.json();
}

function featureOptions(selected) { return Object.entries(FEATURES).map(([key, label]) => `<option value="${key}" ${key === selected ? "selected" : ""}>${label}</option>`).join(""); }

function shell() {
  document.querySelector("#app").innerHTML = `<main class="shell">
    <header class="topbar"><div class="brand"><span class="mark">03</span><div><strong>Segment Atlas</strong><small>Customer clustering laboratory</small></div></div><div class="status" id="status">Connecting to FastAPI…</div></header>
    <section class="hero"><div><p class="eyebrow">PROJECT 03 · UNSUPERVISED LEARNING</p><h1>Find the shape<br><em>of your customers.</em></h1><p class="lede">An interactive evidence surface for a deterministic K-Means experiment. Inspect the geometry, compare candidate models, and keep synthetic hypotheses separate from business truth.</p><div class="hero-tags"><span>artifact-backed</span><span>seed 255</span><span>no target labels</span></div></div><div class="hero-orbit"><div class="orbit"></div><div class="orbit orbit-small"></div><div class="core"><small>SELECTED K</small><strong id="hero-k">—</strong><span>clusters</span></div></div></section>
    <section class="metrics" id="metrics"></section>
    <section class="grid two"><article class="panel"><div class="panel-head"><div><p class="eyebrow">PROFILE LENS</p><h2>Who is in each segment?</h2></div><label>Compare feature<select id="profile-feature">${featureOptions("spend_score")}</select></label></div><div id="profiles" class="profiles"></div></article><article class="panel"><div class="panel-head"><div><p class="eyebrow">VALIDATION</p><h2>Does the shape hold?</h2></div><span class="badge">12 repeated holdouts</span></div><div id="scores" class="scores"></div><p class="note">Silhouette is an internal geometric signal; it is not campaign lift or proof of real customer personas.</p></article></section>
    <section class="panel explorer"><div class="panel-head"><div><p class="eyebrow">POINT EXPLORER</p><h2>Inspect customers, not just averages.</h2><p class="subtle">Every point is returned by FastAPI from <code>explorer_points.csv</code>. Click a point to inspect its assignment diagnostics.</p></div><div class="toolbar"><label>Segment<select id="cluster-filter"><option value="all">All segments</option></select></label><label>Projection<select id="projection"><option value="raw">Raw feature pair</option><option value="pca">PCA visualization</option></select></label><label>X axis<select id="x-feature">${featureOptions("spend_score")}</select></label><label>Y axis<select id="y-feature">${featureOptions("annual_income_k")}</select></label></div></div><div class="explorer-body"><div id="plot" class="plot"></div><aside id="detail" class="detail"><p class="empty">Select a point to inspect one synthetic customer.</p></aside></div><p class="note">PCA is visualization-only. Distance, margin, and confidence are geometry diagnostics in fitted scaled space—not probabilities or outcome predictions.</p></section>
    <section class="grid two"><article class="panel method"><p class="eyebrow">CRISP-DM TRACE</p><h2>From data contract to segment hypothesis.</h2><div class="steps"><div><b>01</b><strong>Understand</strong><span>120 generated customers, 4 numeric features.</span></div><div><b>02</b><strong>Prepare</strong><span>Validate domains; fit StandardScaler on each training split.</span></div><div><b>03</b><strong>Model</strong><span>Compare K-Means candidates k=2…7 with 25 starts.</span></div><div><b>04</b><strong>Evaluate</strong><span>Held-out silhouette, ARI stability, and descriptive diagnostics.</span></div></div></article><article class="panel api-card"><p class="eyebrow">E2E RUN STATUS</p><h2>Live experiment surface.</h2><div id="run-meta" class="run-meta"></div><button id="refresh" class="button">Refresh artifacts ↻</button><p class="note">The browser does not invent metrics. It requests validated JSON from the FastAPI server, which reads the reproducible artifacts and exposes a scoring endpoint.</p></article></section>
    <footer>CMPE 255 · Project 03 · synthetic teaching sample · <a href="../README.md">README</a></footer>
  </main>`;
}

function renderMetrics() { const s = state.summary; $("#hero-k").textContent = s.selected_k; $("#metrics").innerHTML = `<div><span>SELECTED MODEL</span><strong>K-Means · k=${s.selected_k}</strong><small>${s.selected_preprocessing} · ${s.n_customers} customers</small></div><div><span>HELD-OUT SILHOUETTE</span><strong>${fmt(s.validation.silhouette_mean, 4)}</strong><small>± ${fmt(s.validation.silhouette_std, 4)}</small></div><div><span>STABILITY ARI</span><strong>${fmt(s.validation.stability_ari_mean, 4)}</strong><small>across repeated partitions</small></div><div><span>FULL-SAMPLE SILHOUETTE</span><strong>${fmt(s.fit_metrics.silhouette, 4)}</strong><small>descriptive diagnostic</small></div>`; }

function renderProfiles() { const feature = $("#profile-feature").value; const visible = state.profiles.filter((p) => state.cluster === "all" || String(p.cluster) === state.cluster); const max = Math.max(...state.profiles.map((p) => p.means[feature])); $("#profiles").innerHTML = visible.map((p) => `<article class="profile"><div class="profile-top"><span>SEGMENT ${p.cluster}</span><b>${p.count} customers</b></div><h3>${p.name}</h3><p>${p.guidance}</p><div class="bar"><i style="width:${Math.max(8, p.means[feature] / max * 100)}%"></i></div><strong>${FEATURES[feature]} · ${fmt(p.means[feature], 1)}</strong><div class="mini-grid">${Object.entries(FEATURES).map(([key,label]) => `<span>${label}<b>${fmt(p.means[key], key === "purchase_frequency" ? 1 : 0)}</b></span>`).join("")}</div></article>`).join("") || `<p class="empty">No profiles match this filter.</p>`; }

function renderScores() { const rows = state.summary.validation_rows || []; $("#scores").innerHTML = rows.filter((r) => r.preprocessing === state.summary.selected_preprocessing).map((r) => `<div class="score-row ${Number(r.k) === Number(state.summary.selected_k) ? "selected" : ""}"><b>k=${r.k}</b><span><i style="width:${Math.max(3, Number(r.silhouette_mean) * 100)}%"></i></span><strong>${fmt(r.silhouette_mean, 3)}</strong><small>ARI ${fmt(r.stability_ari_mean, 3)}</small></div>`).join(""); }

function renderPlot() { const rows = state.points.filter((p) => state.cluster === "all" || String(p.cluster) === state.cluster); const x = state.projection === "pca" ? "pca_x" : state.x; const y = state.projection === "pca" ? "pca_y" : state.y; if (!rows.length) { $("#plot").innerHTML = `<p class="empty">No points match this segment.</p>`; return; } const width = 760, height = 420, pad = 52; const domain = (key) => { const v = rows.map((p) => Number(p[key])); const min = Math.min(...v), max = Math.max(...v), spread = Math.max(max-min, 1); return [min-spread*.08, max+spread*.08]; }; const xd=domain(x), yd=domain(y); const sx=(v)=>pad+(Number(v)-xd[0])/(xd[1]-xd[0])*(width-pad-22); const sy=(v)=>height-pad-(Number(v)-yd[0])/(yd[1]-yd[0])*(height-pad-22); $("#plot").innerHTML = `<svg viewBox="0 0 ${width} ${height}" role="img" aria-label="Interactive customer segmentation scatter plot"><line class="axis" x1="${pad}" y1="${height-pad}" x2="${width-22}" y2="${height-pad}"/><line class="axis" x1="${pad}" y1="${pad}" x2="${pad}" y2="${height-pad}"/><text x="${width/2}" y="${height-12}" class="axis-label">${esc(state.projection === "pca" ? "PC1" : FEATURES[x])}</text><text x="14" y="${height/2}" class="axis-label" transform="rotate(-90 14 ${height/2})">${esc(state.projection === "pca" ? "PC2" : FEATURES[y])}</text>${rows.map((p) => `<circle cx="${sx(p[x])}" cy="${sy(p[y])}" r="${p.customer_id === state.selected ? 8 : 5}" class="point cluster-${p.cluster} ${p.customer_id === state.selected ? "selected" : ""}" data-id="${esc(p.customer_id)}" tabindex="0" role="button" aria-label="${esc(p.customer_id)}, segment ${p.cluster}, ${esc(p.uncertainty_label)} assignment"/>`).join("")}</svg>`; document.querySelectorAll(".point").forEach((el) => { el.addEventListener("click", () => { state.selected = el.dataset.id; renderPlot(); renderDetail(); }); el.addEventListener("keydown", (e) => { if (e.key === "Enter" || e.key === " ") { e.preventDefault(); state.selected = el.dataset.id; renderPlot(); renderDetail(); } }); }); }

function renderDetail() { const p = state.points.find((row) => row.customer_id === state.selected); if (!p) return; $("#detail").innerHTML = `<p class="eyebrow">POINT INSPECTOR</p><h3>${esc(p.customer_id)} <span>Segment ${p.cluster}</span></h3><div class="pill ${esc(p.uncertainty_label)}">${esc(p.uncertainty_label)} assignment</div><p class="subtle">A synthetic record with a geometry-based diagnostic.</p><div class="detail-grid">${Object.entries(FEATURES).map(([key,label]) => `<div><span>${label}</span><b>${fmt(p[key], key === "purchase_frequency" ? 2 : 1)}</b></div>`).join("")}</div><hr><div class="detail-grid"><div><span>Distance</span><b>${fmt(p.centroid_distance, 3)}</b></div><div><span>Margin</span><b>${fmt(p.assignment_margin, 3)}</b></div><div><span>Confidence proxy</span><b>${fmt(p.assignment_confidence, 3)}</b></div></div>`; }

function wire() { $("#profile-feature").addEventListener("change", renderProfiles); $("#cluster-filter").addEventListener("change", (e) => { state.cluster = e.target.value; renderProfiles(); renderPlot(); renderDetail(); }); $("#projection").addEventListener("change", (e) => { state.projection = e.target.value; [$("#x-feature"), $("#y-feature")].forEach((el) => { el.disabled = state.projection === "pca"; }); renderPlot(); }); $("#x-feature").addEventListener("change", (e) => { state.x = e.target.value; renderPlot(); }); $("#y-feature").addEventListener("change", (e) => { state.y = e.target.value; renderPlot(); }); $("#refresh").addEventListener("click", load); }

async function load() { try { $("#status").textContent = "Checking evidence manifest…"; const evidence = await get("/evidence-status"); if (!evidence.valid) throw new Error(`Evidence blocked: ${evidence.errors.join("; ")}`); const [summary, profiles, points, scores] = await Promise.all([get("/summary"), get("/profiles"), get("/points"), get("/validation")]); state.summary = summary; state.profiles = profiles; state.points = points; state.summary.validation_rows = scores; $("#cluster-filter").innerHTML = `<option value="all">All segments</option>` + state.profiles.map((p) => `<option value="${p.cluster}">Segment ${p.cluster}</option>`).join(""); renderMetrics(); renderProfiles(); renderScores(); if (!state.selected) state.selected = state.points[0]?.customer_id; renderPlot(); renderDetail(); $("#run-meta").innerHTML = `<div><span>API</span><b>FastAPI · connected</b></div><div><span>RUN</span><b>seed ${summary.seed} · ${summary.provenance.python}</b></div><div><span>DATA</span><b>${summary.generator.interpretation}</b></div><div><span>MANIFEST</span><b>SHA-256 set verified</b></div>`; $("#status").textContent = "API connected · manifest verified"; } catch (error) { $("#status").textContent = "Evidence blocked"; $("#run-meta").innerHTML = `<p class="error">${esc(error.message)}. Check the artifact run and refresh.</p>`; } }

shell(); wire(); load();
