"""Generate the offline browser data module from data/transactions.csv."""
from __future__ import annotations

import json
import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(PROJECT_ROOT))
from analysis import DATA_PATH, load_transaction_rows  # noqa: E402

OUTPUT_PATH = PROJECT_ROOT / "data" / "transactions.js"


def rendered_data() -> str:
    rows = [
        {"id": row["transaction_id"], "items": sorted(row["items"])}
        for row in load_transaction_rows(DATA_PATH)
    ]
    return "// Generated by scripts/generate_browser_data.py from data/transactions.csv.\n" \
        "window.TRANSACTION_ROWS = " + json.dumps(rows, indent=2) + ";\n"


def main() -> int:
    expected = rendered_data()
    if "--check" in sys.argv:
        actual = OUTPUT_PATH.read_text(encoding="utf-8") if OUTPUT_PATH.exists() else ""
        if actual != expected:
            print(f"{OUTPUT_PATH} is stale; run python scripts/generate_browser_data.py", file=sys.stderr)
            return 1
        return 0
    OUTPUT_PATH.write_text(expected, encoding="utf-8")
    print(f"Generated {OUTPUT_PATH}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
